// *********************************************************
// Automatically generated by the tool, please do not modify
// *********************************************************

using UnityEngine;
using UnityEngine.UI;


namespace AutoBindNamespace
{
    public partial class AutoBindNamespaceTest
    {
        [SerializeField] private GameObject _goImgIcon;
        [SerializeField] private GameObject _goTxtTitle;
        [SerializeField] private Text _txtTxtTitle;
        [SerializeField] private GameObject _goAutoBindNamespaceTest;
    }
}
