// *********************************************************
// Automatically generated by the tool, please do not modify
// *********************************************************

using UnityEngine;
using UnityEngine.UI;


public partial class AutoBindTest
{
    [SerializeField] private Image _imgImgIcon;
    [SerializeField] private GameObject _goTxtTitle;
    [SerializeField] private Text _txtTxtTitle;
}
